### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by msftcangoblowm** [nine7nine/Onboard_n7n#1]
onboard 1.4.1 was the last release (in 2017) 

marmuta proposed a rewrite to C++ in order to add Wayland support.

[c++ fork by marmuta](https://launchpad.net/onboardosk)

What is the status of:

- onboard (C and python)

- onboardosk (C++)

- What is your intent with this copy of onboard 1.4.1

**Comment by nine7nine** [comment]
I wasn't aware of marmuta's project under this name - I've renamed the repo to avoid any such conflict (not that it should even matter, given that OnboardOSK is a dead project, just like Onboard).

As far as intent - that is a strange question, given the license of Onboard. It's pretty simple though: I use this code for my own purposes. Personally, I think bzr and launchpad are utter crap - so it makes sense to just keep my own local copy in my github.

I hope that satisfies your curiosity. closing this non-issue now.
